version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6
    container_name: agrimaan-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agrimaan-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agrimaan-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - agrimaan-network
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/agrimaan?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your_production_jwt_secret}

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agrimaan-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - agrimaan-network

  # Nginx service for SSL termination and reverse proxy
  nginx:
    image: nginx:alpine
    container_name: agrimaan-nginx
    restart: always
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - agrimaan-network

networks:
  agrimaan-network:
    driver: bridge

volumes:
  mongodb_data: